In [2]:
### Useful Variables ###

NUM_SEEDS = 1 # TODO 应该更大！！！
NUM_ROLLOUTS = 100 # TODO 应该更大！！！！
NUM_AGENTS = 50
SAMPLE_MODE = "top"
NUM_WORKER = 10
NORMALIZE = True
STACK = False

ENV_NAME = "BipedalWalker-v2"
RUN_NAME = "PPO"
DEFAULT_CONFIG = {}

YAML_PATH = "data/300-agents-ppo.yaml"
LOCAL_MODE = False

In [4]:
import numpy as np
import pandas
import ray
import yaml
import seaborn as sns
from sklearn.cluster import KMeans
import pickle

from process_data import make_ordereddict
import logging
from utils import *
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
initialize_ray()

Sucessfully initialize Ray!
Available resources:  {'CPU': 32.0}

In [5]:
# Load data

def load(p):
    with open(p, 'rb') as f:
        ret = pickle.load(f)
    return ret

cka_info = load("data/similarity/ppo-300-agents_rollout100"
                "_seed0_sample-seed0_layer0_cka-info.pkl")
cka_result = load("data/similarity/ppo-300-agents_rollout100"
                  "_seed0_sample-seed0_layer0_cka-result.pkl")

In [6]:
def make_array(cka_result):
    assert isinstance(cka_result, pandas.DataFrame)
    xs = cka_result.x.unique()
    l = len(xs)
    result = np.zeros((l, l))
    for row in cka_result.iterrows():

         x    y     value
0        0    0  1.000000
1        0    1  0.965860
2        0    1  0.965860
3        0    2  0.883340
4        0    2  0.883340
...    ...  ...       ...
89979  295  297  0.894095
89980  295  298  0.958759
89981  295  298  0.958759
89982  295  299  0.977514
89983  295  299  0.977514

[89984 rows x 3 columns]

In [10]:
barr = np.zeros((300, 300))
for _, row in cka_result.iterrows():
    x = int(row.x)
    y = int(row.y)
    barr[x, y] = 1

In [9]:
xs

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False]